export const NEXT_MONTH = 'NEXT_MONTH';
export const PREV_MONTH = 'PREV_MONTH';

export const GET_USER_DATA = 'GET_USER_DATA';
export const STORE_UPDATED_TRACKER = 'STORE_UPDATED_TRACKER';

export const FETCH_TRACKER_SUCCESS = 'FETCH_TRACKER_SUCCESS';
export const FETCH_TRACKER_START = 'FETCH_TRACKER_START';
export const FETCH_TRACKER_FAIL = 'FETCH_TRACKER_FAIL';

export const FETCH_INPUT_FORM_SUCCESS = 'FETCH_INPUT_FORM_SUCCESS';
export const FETCH_INPUT_FORM_FAIL = 'FETCH_INPUT_FORM_FAIL';

export const INPUT_CHANGED = 'INPUT_CHANGED';
export const UPDATE_TRACKER = 'UPDATE_TRACKER';
export const UPDATE_TRACKER_START = 'UPDATE_TRACKER_START';
export const UPDATE_TRACKER_SUCCESS = 'UPDATE_TRACKER_SUCCESS';
export const UPDATE_TRACKER_FAIL = 'UPDATE_TRACKER_FAIL';

export const ENABLE_FORM_EDIT = 'ENABLE_FORM_EDIT';
// export const STORE_TEAM_DATA = 'STORE_TEAM_DATA';


export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT_START = 'AUTH_LOGOUT_START';
export const CLEANUP_TRACKER_REDUCER = 'CLEANUP_TRACKER_REDUCER';

export const CHECK_EMAIL_START = 'CHECK_EMAIL_START';
export const CHECK_EMAIL_SUCCESS = 'CHECK_EMAIL_SUCCESS';
export const CHECK_EMAIL_FAIL = 'CHECK_EMAIL_FAIL';

export const FETCH_USER_DETAILS_SUCCESS = 'FETCH_USER_DETAILS_SUCCESS';
export const FETCH_USER_DETAILS_START = 'FETCH_USER_DETAILS_START';
export const FETCH_USER_DETAILS_FAIL = 'FETCH_USER_DETAILS_FAIL';

export const STORE_CREDENTIALS = 'STORE_CREDENTIALS';
export const SEARCH = 'SEARCH';
